/**
 * weeklyReportService.ts — Weekly Report Generation + Delivery
 *
 * Orchestrates report generation by loading enabled sections from the registry,
 * calling each section handler, assembling the final HTML, and queueing delivery.
 *
 * Extensibility: To add a new report section:
 *   1. INSERT into report_action_registry with a new action_key
 *   2. Create a handler in services/reportSections/ exporting generate(userId, start, end)
 *   3. Users enable it in their config — no code changes to this service needed
 */

const { getAppPool } = require('../config/db');

// Section handler registry (lazy-loaded)
const sectionHandlers: Record<string, any> = {};

function getSectionHandler(handlerModule: string) {
  if (!sectionHandlers[handlerModule]) {
    try {
      sectionHandlers[handlerModule] = require(`./reportSections/${handlerModule}`);
    } catch (err: any) {
      console.error(`Failed to load report section handler '${handlerModule}':`, err.message);
      return null;
    }
  }
  return sectionHandlers[handlerModule];
}

function getEmailHeader(periodStart: string, periodEnd: string): string {
  const start = new Date(periodStart + 'T12:00:00');
  const end = new Date(periodEnd + 'T12:00:00');
  const startStr = start.toLocaleDateString('en-US', { month: 'long', day: 'numeric' });
  const endStr = end.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: #f3f4f6; color: #1f2937; }
    .container { max-width: 640px; margin: 0 auto; background: #ffffff; }
    .header { background: #ffffff; padding: 24px 24px 0 24px; text-align: center; }
    .header img { max-width: 100%; height: auto; }
    .content { padding: 24px; }
    .footer { background: #2d1b4e; padding: 16px 24px; text-align: center; }
    .footer p { margin: 0; font-size: 12px; color: rgba(255,255,255,0.7); }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <img src="https://orthodoxmetrics.com/images/work-report-email-header.png" alt="OrthodoxMetrics" style="max-width: 100%; height: auto;" />
    </div>
    <div class="content">`;
}

function getEmailFooter(): string {
  return `
    </div>
    <div class="footer">
      <p>Generated by OrthodoxMetrics Work Session Tracking</p>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Generate a weekly report for a user.
 */
export async function generateReport(userId: number, periodStart: string, periodEnd: string) {
  const pool = getAppPool();

  // Get user's config (or defaults)
  const [configRows]: any = await pool.query(
    'SELECT * FROM weekly_report_configs WHERE user_id = ?',
    [userId]
  );

  let enabledSections = ['work_sessions', 'tasks_completed', 'highlights', 'anomalies'];
  let configId: number | null = null;

  if (configRows.length > 0) {
    configId = configRows[0].id;
    const raw = configRows[0].enabled_sections;
    if (raw) {
      try {
        enabledSections = typeof raw === 'string' ? JSON.parse(raw) : raw;
      } catch {}
    }
  }

  // Get the registry of available sections
  const [registry]: any = await pool.query(
    'SELECT action_key, handler_module, sort_order FROM report_action_registry ORDER BY sort_order'
  );

  // Create the report run record
  const [runResult]: any = await pool.query(
    `INSERT INTO weekly_report_runs (config_id, user_id, period_start, period_end, status)
     VALUES (?, ?, ?, ?, 'generating')`,
    [configId, userId, periodStart, periodEnd]
  );
  const runId = runResult.insertId;

  try {
    let fullHtml = getEmailHeader(periodStart, periodEnd);
    const reportData: Record<string, any> = {};

    // Process each enabled section in order
    for (const entry of registry) {
      if (!enabledSections.includes(entry.action_key)) continue;

      const handler = getSectionHandler(entry.handler_module);
      if (!handler || !handler.generate) {
        console.warn(`No handler found for section '${entry.action_key}' (module: ${entry.handler_module})`);
        continue;
      }

      try {
        const result = await handler.generate(userId, periodStart, periodEnd);

        // Save section to run items
        await pool.query(
          `INSERT INTO weekly_report_run_items (run_id, action_key, section_html, section_data, sort_order)
           VALUES (?, ?, ?, ?, ?)`,
          [runId, entry.action_key, result.html, JSON.stringify(result.data), entry.sort_order]
        );

        fullHtml += result.html;
        reportData[entry.action_key] = result.data;
      } catch (sectionErr: any) {
        console.error(`Error generating section '${entry.action_key}':`, sectionErr.message);
        fullHtml += `<p style="color: #ef4444;">Error generating ${entry.action_key} section.</p>`;
      }
    }

    fullHtml += getEmailFooter();

    // Update the run with the complete report
    await pool.query(
      `UPDATE weekly_report_runs
       SET status = 'generated', report_html = ?, report_json = ?, generated_at = NOW()
       WHERE id = ?`,
      [fullHtml, JSON.stringify(reportData), runId]
    );

    return {
      run_id: runId,
      status: 'generated',
      period: { start: periodStart, end: periodEnd },
      html: fullHtml,
      data: reportData
    };
  } catch (err: any) {
    await pool.query(
      'UPDATE weekly_report_runs SET status = ?, error_message = ? WHERE id = ?',
      ['failed', err.message, runId]
    );
    throw err;
  }
}

/**
 * Send a generated report via the notification email queue.
 */
export async function sendReport(runId: number, userId: number) {
  const pool = getAppPool();

  const [runs]: any = await pool.query(
    'SELECT * FROM weekly_report_runs WHERE id = ? AND user_id = ?',
    [runId, userId]
  );

  if (runs.length === 0) throw new Error('Report run not found');
  const run = runs[0];

  if (!run.report_html) throw new Error('Report has no content — generate it first');

  // Get recipients from config
  let recipients: string[] = [];
  if (run.config_id) {
    const [configRows]: any = await pool.query(
      'SELECT recipients FROM weekly_report_configs WHERE id = ?',
      [run.config_id]
    );
    if (configRows.length > 0) {
      const raw = configRows[0].recipients;
      try {
        recipients = typeof raw === 'string' ? JSON.parse(raw) : raw;
      } catch {}
    }
  }

  // If no configured recipients, send to the user's own email
  if (recipients.length === 0) {
    const [userRows]: any = await pool.query(
      'SELECT email FROM users WHERE id = ?',
      [userId]
    );
    if (userRows.length > 0) {
      recipients = [userRows[0].email];
    }
  }

  if (recipients.length === 0) {
    throw new Error('No recipients configured and no user email found');
  }

  // Update status
  await pool.query('UPDATE weekly_report_runs SET status = ? WHERE id = ?', ['sending', runId]);

  // Queue emails via the notification system
  const startStr = typeof run.period_start === 'string' && run.period_start.includes('T') ? run.period_start.split('T')[0] : run.period_start;
  const endStr = typeof run.period_end === 'string' && run.period_end.includes('T') ? run.period_end.split('T')[0] : run.period_end;
  const startDate = new Date(startStr + 'T12:00:00');
  const endDate = new Date(endStr + 'T12:00:00');
  const subject = `Weekly Work Report — ${startDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} to ${endDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;

  for (const email of recipients) {
    try {
      // Direct insert into notification_queue (same pattern as notificationService)
      // notification_type_id 90 = 'weekly_digest'
      await pool.query(
        `INSERT INTO notification_queue
          (user_id, notification_type_id, recipient_email, subject, message, html_message, priority, delivery_method, scheduled_at, status)
         VALUES (?, 90, ?, ?, ?, ?, 'normal', 'email', NOW(), 'pending')`,
        [userId, email, subject, 'See HTML version of this email for the full report.', run.report_html]
      );
    } catch (queueErr: any) {
      console.error(`Failed to queue report email to ${email}:`, queueErr.message);
    }
  }

  await pool.query(
    'UPDATE weekly_report_runs SET status = ?, sent_at = NOW() WHERE id = ?',
    ['sent', runId]
  );
}

/**
 * Process all scheduled weekly reports. Called by cron.
 * Finds configs where today matches schedule_day and current hour matches schedule_hour.
 */
export async function processWeeklyReports() {
  const pool = getAppPool();
  const now = new Date();
  const dayOfWeek = now.getDay() === 0 ? 7 : now.getDay(); // 1=Mon...7=Sun
  const hourUTC = now.getUTCHours();

  console.log(`[WeeklyReport] Processing reports for day=${dayOfWeek}, hour_utc=${hourUTC}`);

  // Find enabled configs matching today's day
  // Note: timezone handling is simplified — we match on schedule_day and approximate hour
  const [configs]: any = await pool.query(
    `SELECT wrc.*, u.email as user_email
     FROM weekly_report_configs wrc
     JOIN users u ON u.id = wrc.user_id
     WHERE wrc.is_enabled = 1 AND wrc.schedule_day = ?`,
    [dayOfWeek]
  );

  if (configs.length === 0) {
    console.log('[WeeklyReport] No configs match today');
    return;
  }

  // Calculate last week's period
  const periodEnd = new Date(now);
  periodEnd.setDate(now.getDate() - 1);
  const periodStart = new Date(periodEnd);
  periodStart.setDate(periodEnd.getDate() - 6);

  const startStr = periodStart.toISOString().split('T')[0];
  const endStr = periodEnd.toISOString().split('T')[0];

  for (const config of configs) {
    try {
      // Check if we already ran this report for this period
      const [existingRuns]: any = await pool.query(
        `SELECT id FROM weekly_report_runs
         WHERE user_id = ? AND period_start = ? AND period_end = ? AND status IN ('generated', 'sent')`,
        [config.user_id, startStr, endStr]
      );

      if (existingRuns.length > 0) {
        console.log(`[WeeklyReport] Already ran for user ${config.user_id}, skipping`);
        continue;
      }

      console.log(`[WeeklyReport] Generating for user ${config.user_id} (${config.user_email})`);
      const report = await generateReport(config.user_id, startStr, endStr);
      await sendReport(report.run_id, config.user_id);
      console.log(`[WeeklyReport] Sent report to user ${config.user_id}`);
    } catch (err: any) {
      console.error(`[WeeklyReport] Failed for user ${config.user_id}:`, err.message);
    }
  }
}

/**
 * Auto-end stale sessions (active > 16 hours). Called by hourly cron.
 */
export async function autoEndStaleSessions() {
  const pool = getAppPool();

  const [stale]: any = await pool.query(
    `SELECT id, user_id, started_at FROM work_sessions
     WHERE status = 'active' AND started_at < DATE_SUB(NOW(), INTERVAL 16 HOUR)`
  );

  if (stale.length === 0) return;

  console.log(`[WorkSessions] Auto-ending ${stale.length} stale session(s)`);

  for (const session of stale) {
    try {
      await pool.query(
        `UPDATE work_sessions
         SET status = 'completed',
             ended_at = NOW(),
             duration_seconds = TIMESTAMPDIFF(SECOND, started_at, NOW()),
             end_context = '{"auto_ended": true, "reason": "stale_session_16h"}',
             updated_at = NOW()
         WHERE id = ?`,
        [session.id]
      );

      await pool.query(
        `INSERT INTO work_session_events (work_session_id, event_type, event_timestamp, metadata_json)
         VALUES (?, 'auto_ended', NOW(), ?)`,
        [session.id, JSON.stringify({
          reason: 'stale_session_16h',
          started_at: session.started_at,
          elapsed_hours: Math.floor((Date.now() - new Date(session.started_at).getTime()) / 3600000)
        })]
      );
    } catch (err: any) {
      console.error(`[WorkSessions] Failed to auto-end session ${session.id}:`, err.message);
    }
  }
}
